fullnameOverride: $T-Service$
port: {{.port}}
key1: "value1"
replicaCount: 1

imagePullSecretsName: "default-registry-secret"
image:
  repository: "koderover.tencentcloudcr.com/koderover-demo/$T-Service$"
  tag: "latest"

resources:
  requests:
    cpu: 50m
    mem: 50Mi
  limits:
    cpu: 50m
    mem: 50Mi
