fullnameOverride: $T-Service$
replicaCount: 1
port: {{.port}}

imagePullSecretsName: "default-registry-secret"

image:
  repository: "koderover.tencentcloudcr.com/koderover-demo/$T-Service$"
  tag: "latest"

resources:
  requests:
    cpu: 12m
    mem: 12Mi

  limits:
    cpu: 20m
    mem: 20Mi
